### ISSUE TITLE
Does this module works with ReactiveFormsModule

### ISSUE THREAD

**Issue by Redigast13** [clbond/ng2-redux-form#12]
I know two types of forms in angular 2. Template driven forms and reactive forms. [Here is](https://angular.io/docs/ts/latest/cookbook/form-validation.html) a chapter about form validation in this form types. ng2-redux-form module works fine with template-driven forms. But if I use reactive forms with   formGroup and form controls, then ng2-redux-form module doesn't work. There is no actions @@ng2-redux-form/FORM_CHANGED on inputs changed. 
Does this module work only with template-driven forms?

**Comment by clbond** [comment]
Yes. The purpose of the library is to enable you to build template-driven forms that are bound to Redux state. `FormBuilder` is bad and you can't use it with `ng2-redux-form`-controlled forms.
