### ISSUE TITLE
Babel should be in devDependencies or removed

### ISSUE THREAD

**Issue by marinho** [clbond/ng2-redux-form#7]
Searching for `babel` mentions through the source code points out it's not necessary to keep them in `dependencies` key in `package.json`:

https://github.com/clbond/ng2-redux-form/search?utf8=%E2%9C%93&q=babel

To be honest, I think it's even better to remove its dependency at all, as it is barely used and could easily be replaced by TypeScript in this stack.

**Comment by clbond** [comment]
We use awesome-typescript-loader, which uses TypeScript and Babel together. Closing

**Comment by marinho** [comment]
So, why have it in `dependencies` then? both TypeScript and Babel aren't necessary for going production, they are `devDependencies` too.
